# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Bus_pb2 as Bus__pb2


class ApolloStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBusDetails = channel.unary_unary(
                '/bus.Apollo/GetBusDetails',
                request_serializer=Bus__pb2.BusDetailsRequest.SerializeToString,
                response_deserializer=Bus__pb2.BusDetailsResponse.FromString,
                )


class ApolloServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBusDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ApolloServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBusDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBusDetails,
                    request_deserializer=Bus__pb2.BusDetailsRequest.FromString,
                    response_serializer=Bus__pb2.BusDetailsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bus.Apollo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Apollo(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBusDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bus.Apollo/GetBusDetails',
            Bus__pb2.BusDetailsRequest.SerializeToString,
            Bus__pb2.BusDetailsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
