# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Bus.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Bus.proto',
  package='bus',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tBus.proto\x12\x03\x62us\"/\n\x11\x42usDetailsRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06number\x18\x02 \x01(\x05\"g\n\x12\x42usDetailsResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06number\x18\x02 \x01(\x05\x12\x17\n\x0fpeople_capacity\x18\x03 \x01(\x05\x12\x1c\n\x14\x61verage_people_count\x18\x04 \x01(\x02\x32L\n\x06\x41pollo\x12\x42\n\rGetBusDetails\x12\x16.bus.BusDetailsRequest\x1a\x17.bus.BusDetailsResponse\"\x00\x62\x06proto3'
)




_BUSDETAILSREQUEST = _descriptor.Descriptor(
  name='BusDetailsRequest',
  full_name='bus.BusDetailsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='bus.BusDetailsRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='number', full_name='bus.BusDetailsRequest.number', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=65,
)


_BUSDETAILSRESPONSE = _descriptor.Descriptor(
  name='BusDetailsResponse',
  full_name='bus.BusDetailsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='bus.BusDetailsResponse.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='number', full_name='bus.BusDetailsResponse.number', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='people_capacity', full_name='bus.BusDetailsResponse.people_capacity', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='average_people_count', full_name='bus.BusDetailsResponse.average_people_count', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=170,
)

DESCRIPTOR.message_types_by_name['BusDetailsRequest'] = _BUSDETAILSREQUEST
DESCRIPTOR.message_types_by_name['BusDetailsResponse'] = _BUSDETAILSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BusDetailsRequest = _reflection.GeneratedProtocolMessageType('BusDetailsRequest', (_message.Message,), {
  'DESCRIPTOR' : _BUSDETAILSREQUEST,
  '__module__' : 'Bus_pb2'
  # @@protoc_insertion_point(class_scope:bus.BusDetailsRequest)
  })
_sym_db.RegisterMessage(BusDetailsRequest)

BusDetailsResponse = _reflection.GeneratedProtocolMessageType('BusDetailsResponse', (_message.Message,), {
  'DESCRIPTOR' : _BUSDETAILSRESPONSE,
  '__module__' : 'Bus_pb2'
  # @@protoc_insertion_point(class_scope:bus.BusDetailsResponse)
  })
_sym_db.RegisterMessage(BusDetailsResponse)



_APOLLO = _descriptor.ServiceDescriptor(
  name='Apollo',
  full_name='bus.Apollo',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=172,
  serialized_end=248,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetBusDetails',
    full_name='bus.Apollo.GetBusDetails',
    index=0,
    containing_service=None,
    input_type=_BUSDETAILSREQUEST,
    output_type=_BUSDETAILSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_APOLLO)

DESCRIPTOR.services_by_name['Apollo'] = _APOLLO

# @@protoc_insertion_point(module_scope)
