version: '3.1'
services:
  mysql:
    image: percona:5.7
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: apollo_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  influxdb: 
    image: tutum/influxdb
    restart: always
    ports:
      - "8083:8083"
      - "8086:8086"
    expose:
      - "8090"
      - "8099"
    environment:
      PRE_CREATE_DB: "wadus"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    links:
      - influxdb