version: '3.1'
services:
  mysql:
    image: percona:5.7
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: apollo_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql