version: '3.1'
services:
  mysql:
    image: percona:5.7
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: apollo_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  influxdb: 
    image: tutum/influxdb
    restart: always
    ports:
      - "8083:8083"
      - "8086:8086"
    expose:
      - "8090"
      - "8099"
    environment:
      PRE_CREATE_DB: "wadus"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    links:
      - influxdb
  kafka:
    image: spotify/kafka
    ports:
      - "9092:9092"
      - "2181:2181"
    environment:
      ADVERTISED_HOST: localhost
      ADVERTISED_PORT: 9092
    command: >
      bash -c
      "(sleep 15s &&
      /opt/kafka_2.11-0.10.1.0/bin/kafka-topics.sh
      --create
      --zookeeper
      localhost:2181 --replication-factor 1 --partitions 1
      --topic quickstart-events &) && (supervisord -n)"
